"""Changed name field to title in Opportunity model

Revision ID: e211220ab8e1
Revises: e10822d03c24
Create Date: 2024-11-19 15:10:00.930041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e211220ab8e1'
down_revision = 'e10822d03c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
